package com.civicpulse.ai;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Parsed AI response from the classification / analysis pipeline.
 * <p>
 * Maps the structured JSON that Gemini is instructed to return:
 * <pre>
 * {
 *   "category":   "Road",
 *   "priority":   "High",
 *   "department": "Public Works",
 *   "summary":    "Large pothole causing traffic disruption."
 * }
 * </pre>
 * Additional fields returned by future prompts (e.g. duplicate score,
 * recommended response text) can be added here without breaking callers.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class AIResponse {

    /** High-level complaint category (e.g. "Road", "Water", "Electricity"). */
    private String category;

    /** Suggested priority level (e.g. "High", "Medium", "Low"). */
    private String priority;

    /**
     * Responsible city department inferred from the complaint
     * (e.g. "Public Works", "Municipal Corporation").
     */
    private String department;

    /** One-sentence human-readable summary of the complaint. */
    private String summary;

    // -----------------------------------------------------------------------
    // Extended fields – populated by future AI use-cases
    // -----------------------------------------------------------------------

    /**
     * Severity / urgency label aligned with the existing Issue entity
     * (CRITICAL | HIGH | MEDIUM | LOW).  Kept separate from {@code priority}
     * so that severity (internal) and priority (AI-generated) can be compared.
     */
    private String severity;

    /**
     * Boolean hint for duplicate-detection use-case.
     * {@code true} when the AI believes a similar complaint already exists.
     */
    private Boolean possibleDuplicate;

    /**
     * Draft citizen-facing response text generated by the AI.
     * Populated by the CITIZEN_RESPONSE_GENERATION use-case.
     */
    private String citizenResponse;

    // -----------------------------------------------------------------------
    // Error / fallback metadata
    // -----------------------------------------------------------------------

    /**
     * {@code true} when the AI call succeeded and the response was parsed
     * without errors.
     */
    @Builder.Default
    private boolean success = true;

    /** Human-readable error message when {@code success} is {@code false}. */
    private String errorMessage;

    // -----------------------------------------------------------------------
    // Factory helpers
    // -----------------------------------------------------------------------

    /**
     * Returns a minimal failure response with the given error message.
     *
     * @param errorMessage description of what went wrong
     * @return a failed {@link AIResponse}
     */
    public static AIResponse failure(String errorMessage) {
        return AIResponse.builder()
                .success(false)
                .errorMessage(errorMessage)
                .category("OTHER")
                .priority("Low")
                .severity("LOW")
                .department("General")
                .summary("Unable to classify complaint at this time.")
                .build();
    }
}
