spring.application.name=civicpulse-ai

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/civicpulse_db
spring.datasource.username=root
spring.datasource.password=Smd20109#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.main.allow-circular-references=true

# Server Port
server.port=8081

# Gemini API
gemini.api.key=YOUR_GEMINI_API_KEY
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent

# JWT
jwt.secret=civicpulse-secret-key-2024-very-long-secret-for-hmac-sha
jwt.expiration=86400000
